site_name: memary Documentation
theme: 
  name: material
  #custom_dir: docs/overrides 
  #extra_css: 
    #- assets/css/extra.css
  logo: https://github.com/kingjulio8238/memary/blob/tool-flexibility/diagrams/memary_logo_bw.png?raw=true #need lime background 
  features: 
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - search.suggest 
    - search.highlight 
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en 
  palette: 
    - scheme: default 
      toggle: 
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode 
      primary: teal 
      accent: purple 
    - scheme: slate 
      toggle: 
        icon: material/toggle-switch 
        name: Switch to light mode 
      primary: teal 
      accent: lime #doesn't seem to edit 
repo_url: https://github.com/kingjulio8238/memary 
repo_name: memary 

extra: 
  social: 
    - icon: fontawesome/brands/github-alt
      link: https://github.com/kingjulio8238/memary
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/JulianSaks #to change 

markdown_extensions:
  - pymdownx.highlight: 
      anchor_linenums: true 
  - pymdownx.inlinehilite 
  - pymdownx.snippets
  - admonition 
  - pymdownx.arithmatex: 
      generic: true 
  - footnotes 
  - pymdownx.details 
  - pymdownx.superfences 
  - pymdownx.mark 
  - attr_list 
  - pymdownx.emoji: 
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/kingjulio8238/memary" target="_blank" rel="noopener">memary labs</a>